name: 'sdf-install'
description: 'Run common installation steps for a NetSuite SDF Project'
inputs:
  ns-account-id:
    description: 'The Account ID of the target NetSuite environment'
    required: true
  ns-token-id:
    description: 'The Token ID for authenticating to the target NetSuite environment'
    required: true
  ns-token-secret:
    description: 'The Token Secret for authenticating to the target NetSuite environment'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    - name: Install JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Install package
      run: npm ci --acceptsuitecloudsdklicense
      shell: bash
    - name: Authenticate project against ${{ inputs.ns-account-id }}
      run: ./node_modules/.bin/suitecloud account:savetoken --account ${{ inputs.ns-account-id }} --authid ${{ inputs.ns-account-id }} --tokenid ${{ inputs.ns-token-id }} --tokensecret ${{ inputs.ns-token-secret }}
      shell: bash
