name: SDF Validation
run-name: validate
on:
  push:
    branches: [main, articles/*]
jobs:
  sdf-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'sandbox' }}
    needs: [unit-test, sdf-validate]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sdf-install
        with:
          ns-account-id: ${{ vars.NS_ACCOUNT_ID }}
          ns-token-id: ${{ secrets.NS_TOKEN_ID }}
          ns-token-secret: ${{ secrets.NS_TOKEN_SECRET }}
      - name: Deploy project to ${{ vars.NS_ACCOUNT_ID }}
        run: npm run deploy
  sdf-validate:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sdf-install
        with:
          ns-account-id: ${{ vars.NS_ACCOUNT_ID }}
          ns-token-id: ${{ secrets.NS_TOKEN_ID }}
          ns-token-secret: ${{ secrets.NS_TOKEN_SECRET }}
      - name: Validate project against ${{ vars.NS_ACCOUNT_ID }}
        run: npm run validate
  unit-test:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'sandbox' }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/sdf-install
        with:
          ns-account-id: ${{ vars.NS_ACCOUNT_ID }}
          ns-token-id: ${{ secrets.NS_TOKEN_ID }}
          ns-token-secret: ${{ secrets.NS_TOKEN_SECRET }}
      - name: Run unit tests
        run: npm test
